spring.application.name=mini-project

# Base de datos
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/db_parkify}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:parkify}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:1234}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true

# Puerto del servidor
server.port=8080
server.error.include-message=never

# JWT
jwt.secret=${JWT_SECRET:TXlUZXN0U2VjcmV0S2V5VGhhdElzTG9uZ0Vub3VnaDEyMw==}
jwt.expiration=${JWT_EXPIRATION:PT10H}

# Frontend origin
frontend.origin=${FRONTEND_URL:http://localhost:5173}

# Configs adicionales
spring.config.import=classpath:content-config.properties,optional:classpath:config.properties
