# ====================================
# Initial App Configuration (#10)
# ====================================
parkify.config.initial.theme-colors.primary=#3445c5
parkify.config.initial.theme-colors.secondary=#FFDE59
parkify.config.initial.feature-flags.recommendations-enabled=true
parkify.config.initial.feature-flags.online-booking-enabled=false